name: Release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Release tagged image'
        uses: Japan7/docker-retag-action@v1
        with:
          previous-tag: ${{ github.sha }}
          new-tags: ${{ github.ref_name }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository }}
